### ISSUE TITLE
acknowledgementCallback,I con't received callback

### ISSUE THREAD

**Issue by liubinduo** [socketio/socket.io-server-java#2]
my client is "socket.io-client": "^4.4.1" and my server is java socket.io-server:3.0.2.
why I con't received callback ?  client received message form server.

public void send(String event, Object[] args, ReceivedByRemoteAcknowledgementCallback acknowledgementCallback)

**Comment by trinopoty** [comment]
Please update to the latest version of the library and let me know if the issue persists.
