### ISSUE TITLE
how send a message to a specific client

### ISSUE THREAD

**Issue by gerardoMed** [socketio/socket.io-server-java#5]
Hello, what is the way to send a event message to a specific client.

**Comment by manikmagar** [comment]
@gerardoMed Every client socket is by default added to its own id room. So, if you have a socket id for the client, you can [broadcast the message](https://trinopoty.github.io/socket.io-server-java/using.html#broadcasting-message-to-room) -

```
namespace.broadcast(targetSocketId, "foo", "bar arg");
```

**Comment by gerardoMed** [comment]
It works, thank you!!!
